language: rust

matrix:
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
  - os: linux
    rust: stable
    env: TARGET=i686-unknown-linux-gnu

before_install:
- sudo ci/install_libs.sh "$TARGET"
install:
- rustup install "$TRAVIS_RUST_VERSION-$TARGET"
- rustup target add "$TARGET" || true
script:
- cargo build --verbose --target="$TARGET"
- cargo test --verbose --target="$TARGET"
- cargo build --verbose --release --target="$TARGET"
- ls -lah "target/$TARGET/release/sniffglue"
- file "target/$TARGET/release/sniffglue"
