[package]
name = "sniffglue"
version = "0.5.0"
description = "Secure multithreaded packet sniffer"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/sniffglue"
categories = ["command-line-utilities"]
readme = "README.md"
exclude = ["pcaps/**/*", "**/*.pcap"]

[lib]
doc = false

[badges]
travis-ci = { repository = "kpcyrd/sniffglue" }

[dependencies]
clap = "2"
threadpool = "1.7"
num_cpus = "1.6"
pcap = "0.7.0"
pktparse = { version = "0.2.2", features = ["derive"] }
nom = "3.2"
dns-parser = "0.7"
tls-parser = "0.5"
dhcp4r = "0.1.0"
ansi_term = "0.11"
reduce = "0.1.1"
atty = "0.2"
env_logger = "0.5"
log = "0.4"
libc = "0.2"
toml = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
users = "0.6"

[target.'cfg(target_os="linux")'.dependencies]
seccomp-sys = "0.1.2"

[dev-dependencies]
boxxy = "0.4"
base64 = "0.9"
